version: '3.1'

networks:
  default:
    external:
      name: sam-network

services:
  dynamo:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ./dynamo:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
