AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    trip

    Rest API to manage trips

Globals:
    Function:
        Timeout: 29
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref TripTable
            ENDPOINT_OVERRIDE: "http://localhost:8000"

Resources:

  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.CreateTripRecord::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       CreateTripRecord:
         Type: Api
         Properties:
           Path: /trip
           Method: post
           
  GetTripsByCountryFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.GetTripsByCountry::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripsByCountry:
         Type: Api
         Properties:
           Path: /trip/{country}
           Method: get
              
  GetTripsByCityFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.GetTripsByCity::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripsByCity:
         Type: Api
         Properties:
           Path: /trip/{country}/findByCity
           Method: get
           RequestParameters:
              - method.request.querystring.city
             
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: country
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: city
          AttributeType: S         
      KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      LocalSecondaryIndexes: 
        - IndexName: cityIndex
          KeySchema: 
            - AttributeName: country
              KeyType: HASH
            - AttributeName: city
              KeyType: RANGE
          Projection:
             ProjectionType: ALL 
      BillingMode: PAY_PER_REQUEST              

Outputs:

    CreateTripRecordFunction:
      Description: "CreateTripRecord Lambda Function ARN"
      Value: !GetAtt CreateTripRecordFunction.Arn
      
    GetTripsByCountryFunction:
      Description: "GetTripsByCountry Lambda Function ARN"
      Value: !GetAtt GetTripsByCountryFunction.Arn
      
    GetTripsByCityFunction:
      Description: "GetTripsByCity Lambda Function ARN"
      Value: !GetAtt GetTripsByCityFunction.Arn
     